name: deploy

on:
  workflow_run:
    workflows: ["delivery"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - name: Aplicar manifests al cluster
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo kubectl apply -f https://raw.githubusercontent.com/${{ github.repository }}/main/k8s/deployment.yaml
            sudo kubectl apply -f https://raw.githubusercontent.com/${{ github.repository }}/main/k8s/service.yaml
            sudo kubectl rollout status deployment/calc-api --timeout=120s
            sudo kubectl get pods
            sudo kubectl get svc calc-api-service
